### ISSUE TITLE
[Error (22)] File(kolbot\d2botdropper.dbj:334) TypeError: findList.findIndex is not a function

### ISSUE THREAD

**Issue by SnubBeef** [dzik87/D2Dropper#20]
[Error (22)] File(kolbot\d2botdropper.dbj:334) TypeError: findList.findIndex is not a function

This is an error that occurs when running regular kolbot as soon as the dropper joins a game to drop an item. I followed all the directions exactly. Please let me know if I have an old version or how I can fix this. Happy to donate.

**Comment by dzik87** [comment]
Hello, 

This means you are using older kolbot version without new methods.
Just get kolbot for dropper from here and you should be good to go - https://github.com/blizzhackers/kolbot

Enjoy

**Comment by ghost** [comment]
Hello @dzik87 I just updated my kolbot via svn with a new checkout from  https://github.com/blizzhackers/kolbot/trunk but I still get that same Issue "..findIndex is not a function". Do you have any ideas? 

D2Bot # is 20.6.7.100 (same as before the update)


/UPDATE:
I just checked the files a lil bit, the findindex is from a polyfill in polyfill.js if I see this correct? The file is here, so maybe theres just some issue with the polyfill not working?

**Comment by ghost** [comment]
Solution:
I downloaded all files from blizzhackers/kolbot via zip and replaced them in my kolbot folder manually. 
The reason it didnt work before was that I used svn to create the repository there, because the first time I installed kolbot it was the old repo (d2bot-with-kolbot), so when i checked out the blizzhacker version before he apparently didnt dl all files.

If somebody runs into the same issue you probably first downloaded the d2bs-with-kolbot(honestly dont understand why that repo still exists.. its only confusing and had many problems with that already) repo like i did so I suggest everyone to delete that and start a fresh install from version. You can save ur keys/profiles by pasting the jsons in the new installation and same with your char js files.
