### ISSUE TITLE
(dropper) Invalid Password

### ISSUE THREAD

**Issue by TinyHoney** [dzik87/D2Dropper#39]
what is wrong with that ?  all my mules are logged from Mulelogger or i logged it myself from "Num6" 

i get this problem 2x times

**Comment by Raywl** [comment]
Hey, did you resolve this issue? I've experienced same here. Just wonder where the Dropper load the ACC/PASS from. The only file defined ACC/PW seems to be muleLogger.js, and I've got correct config in there.
Since this issue, until the last Drop task completed, my Dopper's now stuck and so annoying. Anyway to cancel the previous drop task?

**Comment by vtf88** [comment]
Go  into the .txt files for the drop profiles to clear prior pending drops.
________________________________
